wso2-extensions/identity-integration-ui-templates

- .github/workflows/scripts/release-integration.sh
> $subject
- https://github.com/wso2-extensions/identity-integration-ui-templates/pull/1
> Fix the environment variable name issue

- sandbox/scripts/pre-install.cjs
> Fix the issue of stale data clearing in pre-install script

- .github/workflows/deploy-gh-pages.yml
> Add a specific pnpm version for github pages workflow

- .github/workflows/deploy-gh-pages.yml
> Add pnpm version to the matrix

- .github/workflows/deploy-gh-pages.yml
- sandbox/scripts/pre-install.cjs
> Fix the issues in github workflow and pre install script

- .github/workflows/deploy-gh-pages.yml
- sandbox/apps/markdown-editor/vite.config.ts
> Add support to change deployment base path

- integrations/applications/custom-application/pom.xml
- integrations/applications/custom-protocol-application/pom.xml
- integrations/applications/m2m-application/pom.xml
- integrations/applications/mobile-application/pom.xml
- integrations/applications/single-page-application/pom.xml
- integrations/applications/traditional-web-application/pom.xml
- integrations/pom.xml
> This PR is for testing the Maven build process and release functionality using the Jenkins job.
> [Testing-4] Move maven release plugin to the parent pom

- integrations/pom.xml
> [Testing-8] Update maven deploy plugin configuration

- integrations/applications/custom-application/pom.xml
- integrations/applications/custom-protocol-application/pom.xml
- integrations/applications/m2m-application/pom.xml
- integrations/applications/mobile-application/pom.xml
- integrations/applications/single-page-application/pom.xml
- integrations/applications/traditional-web-application/pom.xml
- integrations/pom.xml
- integrations/zip.xml
> [Testing-9] Add maven-assembly plugin to create zip artifact

- integrations/applications/custom-application/pom.xml
- integrations/applications/custom-protocol-application/pom.xml
- integrations/applications/m2m-application/pom.xml
- integrations/applications/mobile-application/pom.xml
- integrations/applications/single-page-application/pom.xml
- integrations/applications/traditional-web-application/pom.xml
- integrations/pom.xml
> [Testing-10] Add skipAssembly configuration to the parent pom

- integrations/pom.xml
> Add support for inherited properties in the assembly plugin

- tools/cli/update-version.js
- tools/cli/utils.js
Previously, updated template versions were generated incorrectly, lacking periods and concatenating extra components due to a missing break after identifying the release type. This PR resolves the issue and adds success messages for each file with the updated version.
> [Bug] Fix version generating issue

- .github/workflows/check-templates-versions.yml
Since template versions are managed separately, anyone updating the template content needs to run a script manually to update the template versions. This action validates whether the version updates have been performed correctly; if they are not updated, this check will fail, and PR merging will be blocked. This is a test, and a series of follow-up PRs will be added to address any issues that arise during this process.
> [Testing-1] Add an action to check template versions

- .github/workflows/check-templates-versions.yml
> $subject
- https://github.com/wso2-extensions/identity-integration-ui-templates/pull/28
> [Testing-2] Remove unnecessary configurations from action yml 

- integrations/pom.xml
> $subject
- https://github.com/wso2-extensions/identity-integration-ui-templates/pull/31
> [Testing-2] Revert the pom change in #31 PR

- .github/workflows/check-templates-versions.yml
- tools/cli/update-version.js
- tools/cli/utils.js
This will address the issue of updating template versions when a new template is added to the repository, and the upstream repository doesn't already contain it.
- https://github.com/wso2-extensions/identity-integration-ui-templates/issues/33
> Fix the version checking issue

- integrations/notification-providers/firebase/pom.xml
- integrations/notification-providers/firebase/resources/info.json
- integrations/notification-providers/firebase/resources/metadata.json
- integrations/notification-providers/firebase/resources/template.json
- integrations/pom.xml
This PR will add the resources required to render the UI components related to Firebase Cloud messaging service used as one of the Push notification provider in Identity server
> Add UI templates for firebase push notification provider

- integrations/applications/mcp-client-application/resources/info.json
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
New application templates should appear last, hence changing the display order property of the MCP client application template
> Change the display order of the MCP client application

- integrations/applications/mcp-client-application/resources/info.json
- integrations/applications/mcp-client-application/resources/metadata.json
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject
> Enable advanced tab in mcp client template

- integrations/applications/mcp-client-application/resources/info.json
- integrations/applications/mcp-client-application/resources/metadata.json
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject
> Add public client option to mcp client app template
